### ISSUE TITLE
object is not an instance of declaring class error

### ISSUE THREAD

**Issue by ertugrulcetin** [clojure-goes-fast/clj-memory-meter#6]
I tried to run on `clojure:openjdk-11-lein-2.9.1` and `clojure:openjdk-13-lein-2.9.1` [Dockerfile], but got exceptions all the time. Also added `-Djdk.attach.allowAttachSelf` flag.

Getting this error:
```
(mm/measure my-atom :bytes true)

java.lang.IllegalArgumentException: object is not an instance of declaring class
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:567)
 at clj_memory_meter.core$add_url_to_classloader_reflective.invokeStatic(core.clj:35)
 at clj_memory_meter.core$add_url_to_classloader_reflective.invoke(core.clj:28)
 at clj_memory_meter.core$fn__20594.invokeStatic(core.clj:67)
 at clj_memory_meter.core$fn__20594.invoke(core.clj:62)
 at clojure.lang.Delay.deref(Delay.java:42)
 at clojure.core$deref.invokeStatic(core.clj:2320)
 at clojure.core$deref.invoke(core.clj:2306)
 at clj_memory_meter.core$mk_vm.invokeStatic(core.clj:79)
 at clj_memory_meter.core$mk_vm.invoke(core.clj:78)
 at clj_memory_meter.core$load_jamm_agent.invokeStatic(core.clj:85)
 at clj_memory_meter.core$load_jamm_agent.invoke(core.clj:84)
 at clj_memory_meter.core$fn__20602.invokeStatic(core.clj:90)
 at clj_memory_meter.core$fn__20602.invoke(core.clj:90)
 at clojure.lang.Delay.deref(Delay.java:42)
 at clojure.core$deref.invokeStatic(core.clj:2320)
 at clojure.core$deref.invoke(core.clj:2306)
 at clj_memory_meter.core$fn__20604.invokeStatic(core.clj:95)
 at clj_memory_meter.core$fn__20604.invoke(core.clj:95)
 at clojure.lang.Delay.deref(Delay.java:42)
 at clojure.core$deref.invokeStatic(core.clj:2320)
 at clojure.core$deref.invoke(core.clj:2306)
 at clj_memory_meter.core$measure.invokeStatic(core.clj:122)
 at clj_memory_meter.core$measure.doInvoke(core.clj:112)
 at clojure.lang.RestFn.invoke(RestFn.java:439)
 at myapp.controller$fn__20716$fn__20717$fn__20718.invoke(controller.clj:226)
 at clojure.lang.AFn.applyToHelper(AFn.java:152)
 at clojure.lang.AFn.applyTo(AFn.java:144)
 at clojure.core$apply.invokeStatic(core.clj:665)
 at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
 at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
 at clojure.lang.RestFn.invoke(RestFn.java:425)
 at clojure.lang.AFn.applyToHelper(AFn.java:156)
 at clojure.lang.RestFn.applyTo(RestFn.java:132)
 at clojure.core$apply.invokeStatic(core.clj:669)
 at clojure.core$bound_fn_STAR_$fn__5749.doInvoke(core.clj:2003)
 at clojure.lang.RestFn.invoke(RestFn.java:397)
```

**Comment by ertugrulcetin** [comment]
@alexander-yakushev any ideas?

**Comment by alexander-yakushev** [comment]
I've just tried it with `clojure:openjdk-11-lein-2.9.1` image and it worked. What is the sequence of steps you perform?

**Comment by ertugrulcetin** [comment]
I've found a way, forked the lib did some changes. Thanks,

**Comment by alexander-yakushev** [comment]
What did you change exactly? This can be useful for others:)

**Comment by ertugrulcetin** [comment]
@alexander-yakushev Sure, I've used [Metabase's add-url-to-classpath!](https://github.com/metabase/metabase/blob/8f4b1022719280b88c7fa8fc7239a3e688997fe1/src/metabase/plugins/classloader.clj#L135). I guess some other users had this issue before and I'm not the only one so you might want update code with the code below. Here is the updated code:

```clojure
(def ^:private tools-jar-classloader
  (delay
    (let [tools-jar (tools-jar-url)
          loader    (cl/the-top-level-classloader)
          dynamic?  (boolean (#{"clojure.lang.DynamicClassLoader" "boot.AddableClassLoader"} (.getName (class loader))))]
      (println [loader dynamic?])
      (if dynamic?
        (try
          (.addURL loader tools-jar)
          (catch Exception e
            (log/error "dynamic? loading threw exception: " (.getMessage e))
            (cl/add-url-to-classpath! tools-jar)))
        (cl/add-url-to-classpath! tools-jar))
      loader)))
```
